[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nhsmm"
version = "0.2.0-alpha.1"
description = "Neural Hidden Semi-Markov Model (HSMM) implementation in PyTorch"
readme = "README.md"
requires-python = ">=3.9"
keywords = ["HSMM", "Neural HSMM", "PyTorch", "sequence modeling", "temporal modeling"]
authors = [
    { name = "AWA", email = "dev@awa.si" }
]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: Apache 2.0 License",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

dependencies = [
    "torch>=2.0",
    "numpy>=1.24",
    "scipy>=1.10",
    "scikit-learn>=1.2",
    "optuna>=3.0",
    "tqdm>=4.66",
]

[project.urls]
Homepage = "https://github.com/awa-si/NHSMM"
Repository = "https://github.com/awa-si/NHSMM"
